#' Get KPI Metric Choices
#'
#' Data expected by the app to display on the UI on initial session start
#'
#' @return A list containing available metric choices for user selection
#'
get_kpi_choices <- function() {
  list(
    `Descriptive` = list(
      `Total Sales Per Month` = "total_sales",
      `Days with Orders in Month` = "order_days"
    ),
    `Average Velocity` = list(
      `Orders Per Day` = "orders_per_day",
      `Sales Per Day` = "dollars_per_day"
    ),
    `Average Ticket Size` = list(
      `Orders without House Products` = "ave_order_size_no_house",
      `Orders with House Products` = "ave_order_size_house",
      `Sales Per Order on House Products` = "ave_house_dollars_per_order",
      `Ticket Premium on House Products` = "house_order_premium"
    ),
    `Share (%) of all` = list(
      `Orders Containing House Products` = "pct_orders_house",
      `Dollars Spent on House Products` = "pct_sales_house"
    )
  )
}


#' Get KPI Metric Summary
#'
#' Function called by app server to load metric value based on selected KPI
#'
#' @param appdata App dataset
#' @param fac facility selection
#' @param pd period selection
#' @param var kpi selection
#'
#' @return A list object containing data for the selected KPI, expected by the app
#'
get_kpi_definition <- function(appdata, fac, pd, var) {
  if (fac != "") {
    kpi_value <- appdata[
      store == fac &
        period == pd &
        kpi_name == var,
      mean(kpi_value, na.rm = TRUE)
    ]

    ## get body of infobox
    var_definition <- switch(
      var,
      order_days = list(
        def = "Number of Days in Period with Orders",
        icn = "calendar",
        val = round(kpi_value, 0)
      ),
      orders_per_day = list(
        def = "Average Orders Per Day for Period",
        icn = "shopping-cart",
        val = round(kpi_value, 0)
      ),
      total_sales = list(
        def = "Total Sales in Period",
        icn = "dollar-sign",
        val = scales::dollar(kpi_value, accuracy = 1)
      ),
      dollars_per_day = list(
        def = "Sales Dollars Per Day in Period",
        icn = "dollar-sign",
        val = scales::dollar(kpi_value, accuracy = 1)
      ),
      ave_order_size_no_house = list(
        def = "Average order size when House products are NOT purchased",
        icn = "dollar-sign",
        val = scales::dollar(kpi_value, accuracy = 1)
      ),
      ave_order_size_house = list(
        def = "Average order size when House products are purchased",
        icn = "dollar-sign",
        val = scales::dollar(kpi_value, accuracy = 1)
      ),
      ave_house_dollars_per_order = list(
        def = "Average dollars spent per order for orders that include House products",
        icn = "dollar-sign",
        val = scales::dollar(kpi_value, accuracy = 1)
      ),
      house_order_premium = list(
        def = "Average order size premium for orders that include House products",
        icn = "percentage",
        val = scales::percent(kpi_value, accuracy = .1)
      ),
      pct_orders_house = list(
        def = "Percent of all orders that contain any House products",
        icn = "percentage",
        val = scales::percent(kpi_value, accuracy = .1)
      ),
      pct_sales_house = list(
        def = "Percent of sales dollars generated by House products",
        icn = "percentage",
        val = scales::percent(kpi_value, accuracy = .1)
      )
    )

    shinydashboard::infoBox(
      title = fac,
      value = var_definition$val,
      subtitle = paste(var_definition$def, "(Store Average)"),
      icon = shiny::icon(var_definition$icn),
      color = "aqua",
      width = 12,
      href = NULL,
      fill = FALSE
    )
  } else {
    shinydashboard::infoBox(
      title = "Store Average",
      value = "",
      subtitle = "",
      color = "aqua",
      width = 12,
      href = NULL,
      fill = FALSE
    )
  }
}
