#' Plot Store Employee Performance
#'
#' @param appdata App dataset
#' @param fac facility selection
#' @param pd period selection
#' @param var kpi selection
#'
#' @return ggplot object
#'
plotEmployees <- function(appdata, fac, pd, var) {
  if (fac == "") {
    return(NULL)
  }

  pdata <- appdata[
    store == fac & period == pd & kpi_name == var,
    !c("store", "period", "kpi_name"), with = FALSE
  ]
  pdata[is.na(kpi_value) | kpi_value < 0, kpi_value := 0]
  pdata[, employee := factor(employee, levels = pdata[order(kpi_value), employee])]

  ## Text for the plot title
  ##
  p_title <- switch(
    var,
    order_days = "Number of Days with Orders",
    orders_per_day = "Average Orders Per Day",
    total_sales = "Total Sales in Period",
    dollars_per_day = "Sales Dollars Per Day",
    ave_order_size_no_house = "Average Order Size without House Products",
    ave_order_size_house = "Average Order Size when House Products are Purchased",
    ave_house_dollars_per_order = "Average Dollars Spent Per Order on House Products",
    house_order_premium = "Average Order Premium when House Products are Purchased",
    pct_orders_house = "Percent of Orders that Contain House Products",
    pct_sales_house = "Percent of All Sales Generated by House Products"
  )

  ## Text for the subtitle
  ##
  curr <- floor_date(today(), "months")

  pd_text <- switch(
    pd,
    "Month-To-Date" = paste0(month(curr, label = TRUE), " 1st - Present"),
    "Last Month" = {
      start <- format.Date(curr - months(1), "%b 1")
      stop <- format.Date(curr - 1, "%b %d")
      paste0(start, " - ", stop)
    },
    "Historical" = {
      stop <- format.Date(curr - months(1) - 1, "%b %d")
      str_glue("All Time (Prior to {stop})")
    }
  )
  p_subtitle <- str_glue("{fac} | {pd_text}")

  ## Show custom plot when kpi_name is Ave House Dollars Per Order
  ##
  if (var == "ave_house_dollars_per_order") {
    var2 <- "ave_order_size_house"
    tmp <- appdata[
      store == fac & period == pd & kpi_name == var2,
      !c("store", "period", "kpi_name"), with = FALSE
    ]
    setnames(tmp, "kpi_value", "order_size")

    setkeyv(tmp, "employee")
    setkeyv(pdata, "employee")

    pdata[tmp, delta := order_size - kpi_value]

    ## TODO: This results in negative for some employees. Zero out for now
    pdata[delta < 0, delta := 0]

    pdata2 <- melt(pdata, id.vars = "employee")

    pdata2[, employee := factor(employee, levels = pdata[order(kpi_value), employee])]
    setkeyv(pdata2, "employee")

    pdata2[, lab := scales::dollar(value, accuracy = 1)]

    pdata2[value == 0, lab := NA]
    pdata2[variable == "delta", order_dollars := "Non-House Products"]
    pdata2[variable == "kpi_value", order_dollars := "House Products"]

    pdata2[, order_dollars :=
             factor(order_dollars, levels = c("Non-House Products", "House Products"))]

    pdata2[, pos := sum(value), employee]

    labels_1 <- pdata2[order_dollars == "House Products"][!is.na(lab)]
    labels_2 <- pdata2[order_dollars == "Non-House Products"][!is.na(lab)]

    p <- ggplot(pdata2, aes(value, employee, fill = order_dollars)) +
      geom_bar(orientation = "y",
               stat = "identity",
               alpha = .6) +
      geom_text(aes(label = lab), data = labels_1,
                hjust = 1) +
      geom_text(aes(x = pos, label = lab), data = labels_2,
                hjust = 1, color = "black", size = 3) +
      ggtitle(p_title, p_subtitle) +
      scale_y_discrete(expand = c(0, 0)) +
      scale_x_continuous(expand = c(0, 0, .15, 0)) +
      ggthemes::theme_few() +
      theme(
        legend.title = element_blank(),
        legend.position = "top",
        legend.justification = c(0,0),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank()
      )
    p
  } else {
    setkeyv(pdata, "employee")

    ## create the labels based on which measure kpi_name is selected
    ##
    dollar_vars <- c(
      "total_sales",
      "dollars_per_day",
      "ave_order_size_no_house",
      "ave_order_size_house",
      "ave_house_dollars_per_order"
    )
    percent_vars <- c(
      "house_order_premium",
      "pct_orders_house",
      "pct_sales_house"
    )
    if (var %in% dollar_vars) {
      if (str_detect(var, "sales|^dollars"))
        pdata[, lab := scales::dollar(kpi_value, accuracy = 1)]
      else {
        pdata[, lab := scales::dollar(kpi_value, accuracy = .1)]
      }
      storeAverage <- data.table(
        kpi_value = pdata[, mean(kpi_value, na.rm = TRUE)],
        lab = pdata[, scales::dollar(mean(kpi_value, na.rm = TRUE), accuracy = 1)]
      )
    } else if (var %in% percent_vars) {
      pdata[, lab := scales::percent(kpi_value, accuracy = .1)]
      storeAverage <- data.table(
        kpi_value = pdata[, mean(kpi_value, na.rm = TRUE)],
        lab = pdata[, scales::percent(mean(kpi_value, na.rm = TRUE), accuracy = .1)]
      )
    } else {
      pdata[, lab := kpi_value]
      storeAverage <- data.table(
        kpi_value = pdata[, mean(kpi_value, na.rm = TRUE)],
        lab = round(pdata[, mean(kpi_value, na.rm = TRUE)], 0)
      )
    }
    storeAverage[, lab := paste0("italic(Average): italic('", lab, "')")]
    pdata[, is_above := kpi_value > mean(kpi_value)]
    pdata[kpi_value > mean(kpi_value) + 1.96*sd(kpi_value)/sqrt(.N), perfgroup := "high"]
    pdata[kpi_value < mean(kpi_value) - 1.96*sd(kpi_value)/sqrt(.N), perfgroup := "low"]
    pdata[is.na(perfgroup), perfgroup := "mid"]
    pdata[, perfgroup := factor(perfgroup,
                                levels = c("high", "mid", "low"),
                                labels = c("High Performance", "Average Range", "Low Performance"))]

    col_above <- "seagreen3"
    col_range <- "royalblue1"
    col_below <- "coral"

    ## Transform x axis values for chart readability
    ##
    xmin <- pdata[, .95 * min(kpi_value)]
    my_trans <- scales::trans_new(
      name = "mybar",
      transform = function(x) x - xmin,
      inverse = function(x) x + xmin
    )

    ## create and return plot
    ##
    p <- ggplot(pdata, aes(kpi_value, employee)) +
      geom_vline(aes(xintercept = kpi_value), storeAverage,
                 linetype = 5, color = "blue2", linewidth = .5) +
      geom_bar(aes(fill = perfgroup),
               orientation = "y",
               stat = "identity",
               alpha = .6) +
      geom_text(aes(label = lab),
                hjust = 0) +
      geom_text(aes(x = kpi_value, y = 2, label = lab), storeAverage,
                hjust = -.05, color = "blue2", parse = TRUE) +
      ggtitle(p_title, p_subtitle) +
      scale_y_discrete(expand = c(0, 0)) +
      scale_x_continuous(trans = my_trans, expand = c(0, 0, .15, 0)) +
      scale_fill_manual(values = c(col_above, col_range, col_below)) +
      ggthemes::theme_few() +
      theme(
        legend.position = "top",
        legend.justification = c(0,0),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank()
      )
    p
  }
}
